NewBundle\Entity\Direccion:
    type: entity
    table: direccion
    repositoryClass: NewBundle\Repository\DireccionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        calle:
            type: string
            length: '30'
        colonia:
            type: string
            length: '30'
        delegacion:
            type: string
            length: '30'
        numero:
            type: integer
    

    lifecycleCallbacks: {  }
